version: '3.7'

services:
  db:
    restart: always
    image: postgres:14-alpine
    user: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.2-alpine
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py fill
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  celery:
    restart: always
    build: .
    container_name: celery
    command: >
      bash -c "celery -A config worker --beat --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./media:/media


volumes:
  pg_data:
  static:
  media:


